name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.x

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run tests
        run: go test -v ./...
